name: md-exafs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.20.0
  - pip
  - pip:
    - ovito>=3.0.0
    - tqdm>=4.60.0
    - tomli>=2.0.0  # For Python < 3.11
    - build  # For building the package
    - pytest  # For testing