name: md-exafs
channels:
  - https://conda.ovito.org
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python=3.10
  - numpy>=1.20.0
  - ovito=3.12.4
  - ase>=3.22.0
  - pip
  - pip:
    - tqdm>=4.60.0
    - tomli>=2.0.0  # For Python < 3.11
    - build  # For building the package
    - pytest  # For testing