# MD-EXAFS Chi Averaging Configuration

[averaging]
# Directory containing FEFF calculation results
input_directory = "feff_calculations"

# Frame range to average (single frame example)
frame_range = [0, 1]

# Output file for averaged chi data
output_file = "chi_avg_example.dat"